#!/bin/bash

# Path to watch and sync
WATCH_PATH=''

# Hosts to sync to
HOSTS_FILE=$ROOT'/hosts.list'

# List of the domains we need to check
DOMAINS_FILE=$ROOT'/domains.list'

# Filename, without extension responsible for monitoring
EXECUTABLE='launch_inotify'

# Command will be used to restart watch
RESTART_COMMAND=$ROOT'/launch_inotify.sh --path='

# Log folder
LOG_FOLDER=$ROOT'/logs/'

# Date format
DATE_FORMAT='%Y/%m/%d %H:%M:%S'
